### ISSUE TITLE
A Trivial Issue: setWireValue(Wire w, long v)

### ISSUE THREAD

**Issue by maxilbert** [akosba/jsnark#4]
public void setWireValue(Wire wire, long v) {
		setWireValue(wire, new BigInteger(v + ""));
	}

For the above method, I found a trivial issue when I occasionally gave a "negative" v.
In this case, "circuitName.in" will have negative signs shown, and the libsnark interface cannot understand negative signs correctly. The prover will fail to create proof.

A temporary fix is as following:

	public void setWireValue(Wire wire, int v) {
		setWireValue(wire, v & 0xffffffffL);
	}
		
	public void setWireValue (Wire wire, Long v) {
		setWireValue(wire, new BigInteger(Long.toUnsignedString(v)));
	}

**Comment by akosba** [comment]
Actually, the implementation does not support negative values on the wires currently. The implementation of negative values is up to the programmer at this point. In the future, there will hopefully be classes that support this on top.

The modifications you suggested will only help to make the program run, but they won't make it run consistently as the programmer expects. For example, if the comparison methods of the Wire class are used (e.g. isGreaterThan) while supporting your modifications, they won't always give consistent results depending on the usage, because they assume unsigned values at this point (in other words, a method may output that a negative number is greater than a positive number if we let the programmer assign negative values on the wires your way). Therefore, I preferred to make the negative values explicitly not supported on the wires in this basic version, until consistent support is added in another version. I will add a clarifying comment later in the code that the setWireValue and other methods only assume unsigned values within 0 and p-1 at this point.

**Comment by Maxilbert** [comment]
Thanks for kind reply.

I agree Jsnark does not support negative and the "negative" is up to the programmer. As for me, I give a 32 bit or 64 bit unsigned value with the first binary bit is 1 (I made quotations to negative). The purpose was to do unsigned arithmetic operations for large integers. I also think it is possible for me to represent real negative by using 2's complement representation, although I did make trails. 

The problem happened when the first binary is one for unsigned values.
